# Generated by Django 2.0.1 on 2018-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='light',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
